extensions = [
]

ghc_flags = ["-X" + ext for ext in extensions] + [
    "-Wall",
    "-fwarn-incomplete-uni-patterns",
    "-fwarn-incomplete-record-updates",
    "-funbox-strict-fields",
]

haskell_library(
    name = "amazonka-amp",
    srcs = glob(["src/**/*.hs", "gen/**/*.hs"]),
    compiler_flags = ghc_flags,
    visibility = ["//amazonka/..."],
    deps = [
        "//amazonka/lib/amazonka-core:amazonka-core",
        "//haskell:base",
    ],
)
